server:
  port: 8080
camunda.bpm:
  database:
    schema-update: true
    type: postgres

spring.datasource:
  url: "jdbc:postgresql://192.168.2.130:5432/core"
  username: postgres
  password: postgres
  platform: postgres
  driverClassName: org.postgresql.Driver